Frontends/MultiShopProject.WebUI/Controllers/DiscountController.cs
using Microsoft.AspNetCore.Mvc;
using MultiShopProject.WebUI.Services.BasketServices;
using MultiShopProject.WebUI.Services.DiscountServices;

namespace MultiShopProject.WebUI.Controllers;

public class DiscountController : Controller
{
    private readonly IDiscountService _discountService;
    private readonly IBasketService _basketService;

    public DiscountController(IDiscountService discountService, IBasketService basketService)
    {
        _discountService = discountService;
        _basketService = basketService;
    }

    [HttpGet]
    public PartialViewResult ConfirmDiscountCoupon()
    {
        return PartialView();
    }

    [HttpPost]
    public async Task<IActionResult> ConfirmDiscountCoupon(string code)
    {
        var values = await _discountService.GetDiscountCouponCountRate(code);
        var basketValues = await _basketService.GetBasket();
        var totalPriceWithTax = basketValues.TotalPrice + (basketValues.TotalPrice / 100 * 10);
        var totalPriceWithDiscount = totalPriceWithTax - (totalPriceWithTax / 100 * values);
        //ViewBag.totalPriceWithDiscount = totalPriceWithDiscount;

        return RedirectToAction("Index", "ShoppingCart", new { code = code, discountRate = values, totalPriceWithDiscount = totalPriceWithDiscount });

        #region Old Method
        // ikinci yorum satırına aldığımız bölüm
        //var values = _discountService.GetDiscountCode(code);
        //var basketValues = await _basketService.GetBasket();
        //var totalPriceWithTax = basketValues.TotalPrice + (basketValues.TotalPrice / 100 * 10);

        //var totalPriceWithDiscount = totalPriceWithTax - (totalPriceWithTax / 100 * 20);
        //ViewBag.totalPriceWithDiscount = totalPriceWithDiscount;


        // ilk yorum satırına aldığımız bölüm
        //var values = await _basketService.GetBasket();
        //ViewBag.total = values.TotalPrice;
        //var totalPriceWithTax = values.TotalPrice + (values.TotalPrice / 100 * 10);
        //var tax = values.TotalPrice / 100 * 10;
        //ViewBag.totalPriceWithTax = totalPriceWithTax;
        //ViewBag.tax = tax;
        //return View();
        #endregion
    }
}

Frontends/MultiShopProject.WebUI/Views/Discount/ConfirmDiscountCoupon.cshtml
<div class="col-lg-4">
    <form class="mb-30" asp-controller="Discount" asp-action="ConfirmDiscountCoupon" method="post">
        <div class="input-group">
            <input type="text" name="code" value="@ViewBag.code" class="form-control border-0 p-4" placeholder="Kupon Kodunuz">
            <div class="input-group-append">
                <button class="btn btn-primary">Kuponu Uygula</button>
            </div>
            <br />
            <h3></h3>
        </div>
    </form>
    <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Sipariş Özeti</span></h5>
    <div class="bg-light p-30 mb-5">
        <div class="border-bottom pb-2">
            <div class="d-flex justify-content-between mb-1">
                <h6>Ara Toplam</h6>
                <h6>@String.Format("{0:N2}", ViewBag.total) ₺</h6>
            </div>
            <div class="d-flex justify-content-between mb-1">
                <h6 class="font-weight-medium">Kdv Tutarı</h6>
                <h6 class="font-weight-medium">@String.Format("{0:N2}", ViewBag.tax) ₺</h6>
            </div>
            <div class="d-flex justify-content-between mb-1">
                <h6 class="font-weight-medium">İndirim Oranı</h6>
                <h6 class="font-weight-medium">@String.Format("{0} %", ViewBag.discountRate)</h6>
            </div>
            <div class="d-flex justify-content-between mb-1">
                <h6 class="font-weight-medium">İndirimsiz Tutar</h6>
                <h6 class="font-weight-medium">@String.Format("{0:N2}", ViewBag.totalPriceWithTax) ₺</h6>
            </div>
        </div>
        <div class="pt-2">
            <div class="d-flex justify-content-between mt-2">
                <h5>İndirimli Güncel Tutar</h5>
                <h5>@String.Format("{0:N2}", ViewBag.totalPriceWithDiscount) ₺</h5>
            </div>
            <button class="btn btn-block btn-primary font-weight-bold my-3 py-3">Ödeme Adımına Geç</button>
        </div>
    </div>
</div>